{"name": "test_login[test_data2]", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778", "trace": "request = <SubRequest 'driver' for <Function test_login[test_data2]>>\n\n    @pytest.fixture\n    def driver(request):\n        config = ConfigReader()\n        browser = config.get_browser_type()\n>       driver = DriverFactory.create_driver(browser)\n\nconftest.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nutilities\\driver_factory.py:17: in create_driver\n    ChromeDriverManager().install(),\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\chrome.py:32: in install\n    driver_path = self._get_driver_path(self.driver)\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\manager.py:23: in _get_driver_path\n    driver_version = driver.get_version()\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py:41: in get_version\n    return self.get_latest_release_version()\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py:74: in get_latest_release_version\n    validate_response(resp)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresp = <Response [404]>\n\n    def validate_response(resp):\n        if resp.status_code == 404:\n>           raise ValueError(\"There is no such driver by url {}\".format(resp.url))\nE           ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778\n\nC:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\utils.py:80: ValueError"}, "attachments": [{"name": "log", "source": "b3212954-faae-4724-b213-c3681a38f1fd-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "34543320-8844-402e-920d-41afd0668b4a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_data", "value": "{'username': '', 'password': 'password123', 'expected_result': 'failure', 'error_message': 'Warning: Please enter your email address'}"}], "start": 1735548354902, "stop": 1735548354902, "uuid": "b3856d90-0819-4731-b740-51cd78028bbf", "historyId": "46eb232d412cf7a2995e4c238d81d0a6", "testCaseId": "2116f0ad00ab1de0effc54f114dd9496", "fullName": "tests.test_login.TestLogin#test_login", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "로그인"}, {"name": "story", "value": "데이터 기반 로그인 테스트"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "JiHee"}, {"name": "thread", "value": "35048-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}