{"uuid": "961f7c4f-30b5-4ab3-97ac-735e061c589f", "children": ["46522e58-273a-4e0a-abfc-3ab07a4563e9"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_131.0.6778\n", "trace": "  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 924, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\GitHub\\JiHeeChoi.github.io\\Automation\\selenium_test_project\\conftest.py\", line 16, in driver\n    driver = DriverFactory.create_driver(browser)\n  File \"C:\\GitHub\\JiHeeChoi.github.io\\Automation\\selenium_test_project\\utilities\\driver_factory.py\", line 17, in create_driver\n    ChromeDriverManager().install(),\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\chrome.py\", line 32, in install\n    driver_path = self._get_driver_path(self.driver)\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\manager.py\", line 23, in _get_driver_path\n    driver_version = driver.get_version()\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py\", line 41, in get_version\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\driver.py\", line 74, in get_latest_release_version\n    validate_response(resp)\n    ~~~~~~~~~~~~~~~~~^^^^^^\n  File \"C:\\Users\\huyuh\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\webdriver_manager\\utils.py\", line 80, in validate_response\n    raise ValueError(\"There is no such driver by url {}\".format(resp.url))\n"}, "start": 1735548355211, "stop": 1735548355459}], "start": 1735548355211, "stop": 1735548355484}